config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'users/sessions' }

  root "contacts#index"

  resources :contacts do
    get '/page/:page', action: :index, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord

  paginates_per 8

  has_one_attached :image

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true, length: { is: 10 }
  validates :email, presence: true
  validates :company_name, presence: true
  validates :address, presence: true, length: { minimum: 10 }

  validates_uniqueness_of :phone_number, :email


  # validates :image, presence: true, blob: { content_type: 'image/jpg' }

  validate :is_image

  private
  def is_image
    if image.attached? && !image.content_type.in?(%w(image/jpeg image/jpg image/png image/webp))
      image.destroy
      errors.add(:image, "Must Add Only Images with Jpeg/Png format")
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:username, :email)
    end
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit({ roles: [] }, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_action :authenticate_user!, except: %i[home]

  def index
    @contacts = Contact.order(:first_name).page params[:page]
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to @contact
    else
      render :new
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])

    if @contact.update(contact_params)
      redirect_to @contact
    else
      render :edit
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    redirect_to root_path
  end

  private
  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :phone_number, :email, :company_name, :birth_date, :address, :image)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with model: @contact do |form| %>

<div class="form-outline mb-4">
  <%= form.label 'Profile Photo', :class => "form-label" %>
  <%= form.file_field :image, autofocus: true, :id => "form3Example3cg", :class => "form-control form-control-lg" %>
  <% @contact.errors.full_messages_for(:image).each do |message| %>
      <div><%= message %></div>
  <% end %>
</div>

<div class="form-outline mb-4">
  <%= form.label 'First Name', :class => "form-label" %>
  <%= form.text_field :first_name, autofocus: true, :id => "form3Example3cg", :class => "form-control form-control-lg" %>
  <% @contact.errors.full_messages_for(:first_name).each do |message| %>
      <div><%= message %></div>
  <% end %>
</div>

<div class="form-outline mb-4">
  <%= form.label 'Last Name', :class => "form-label" %>
  <%= form.text_field :last_name, autofocus: true, :id => "form3Example3cg", :class => "form-control form-control-lg" %>
  <% @contact.errors.full_messages_for(:last_name).each do |message| %>
      <div><%= message %></div>
  <% end %>
</div>

<div class="form-outline mb-4">
  <%= form.label 'Phone Number', :class => "form-label" %>
  <%= form.number_field :phone_number, autofocus: true, :id => "form3Example3cg", :class => "form-control form-control-lg" %>
  <% @contact.errors.full_messages_for(:phone_number).each do |message| %>
      <div><%= message %></div>
  <% end %>
</div>

<div class="form-outline mb-4">
  <%= form.label 'Email Id', :class => "form-label" %>
  <%= form.email_field :email, autofocus: true, :id => "form3Example3cg", :class => "form-control form-control-lg" %>
  <% @contact.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
  <% end %>
</div>

<div class="form-outline mb-4">
  <%= form.label 'Company Name', :class => "form-label" %>
  <%= form.text_field :company_name, autofocus: true, :id => "form3Example3cg", :class => "form-control form-control-lg" %>
  <% @contact.errors.full_messages_for(:company_name).each do |message| %>
      <div><%= message %></div>
  <% end %>
</div>

<div class="form-outline mb-4">
  <%= form.label 'Date of Birth', :class => "form-label" %>
  <%= form.date_field :birth_date, autofocus: true, :id => "form3Example3cg", :class => "form-control form-control-lg" %>
  <% @contact.errors.full_messages_for(:birth_date).each do |message| %>
      <div><%= message %></div>
  <% end %>
</div>

<div class="form-outline mb-4">
  <%= form.label 'Address', :class => "form-label" %>
  <%= form.text_area :address, autofocus: true, :id => "form3Example3cg", :class => "form-control form-control-lg" %>
  <% @contact.errors.full_messages_for(:address).each do |message| %>
      <div><%= message %></div>
  <% end %>
</div>

<div class="d-flex justify-content-center">
  <%= form.submit "Update Contact", :class => "btn btn-danger btn-lg btn-block" %>
</div>
<% end %>

app/views/contacts/edit.html.erb
<div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Edit Contact</h2>

              <%= render "form", contact: @contact%>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/contacts/index.html.erb
<div class="container py-5">
    <div class="row align-items-center">
        <div class="col-md-6">
            <div class="mb-3">
                <h5 class="card-title">Contact List <span class="text-muted fw-normal ms-2">(<%= @contacts.count %>)</span></h5>
            </div>
        </div>
    </div>

    <div class="row">
        <% @contacts.each do |contact| %>
        <div class="col-xl-3 col-sm-6">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex align-items-center">
                        <% if contact.image.attached? %>
                            <div><%= image_tag(contact.image, :class => "avatar-md rounded-circle img-thumbnail") %></div>
                        <% else %>
                            <div><img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="" class="avatar-md rounded-circle img-thumbnail" /></div>
                        <% end %>
                        <div class="flex-1 ms-3">
                            <h5 class="font-size-16 mb-1"><a href="#" class="text-dark"><%= contact.first_name %> <%= contact.last_name %></a></h5>
                        </div>
                    </div>
                    <div class="mt-3 pt-1">
                        <p class="text-muted mb-0"><i class="mdi mdi-phone font-size-15 align-middle pe-2 text-danger"></i> <%= contact.phone_number %></p>
                        <p class="text-muted mb-0 mt-2"><i class="mdi mdi-email font-size-15 align-middle pe-2 text-danger"></i> <%= contact.email %></p>
                        <p class="text-muted mb-0 mt-2"><i class="mdi mdi-google-maps font-size-15 align-middle pe-2 text-danger"></i> <%= contact.address %></p>
                    </div>
                    <div class="d-flex gap-2 pt-4">
                        <%= link_to 'View Contact', contact, :class=>"btn btn-danger btn-sm w-50" %>
                        <%# <button type="button" class="btn btn-soft-primary btn-sm w-50"><i class="bx bx-user me-1"></i> Profile</button> %>
                        <%# <button type="button" class="btn btn-primary btn-sm w-50"><i class="bx bx-message-square-dots me-1"></i> Contact</button> %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
    </div>


    <div class="row g-0 align-items-center pb-4">
        <div class="col-sm-6">
            <div><p class="mb-sm-0">Showing 1 to 3 of 8 entries</p></div>
        </div>
        <div class="col-sm-6">
            <div class="float-sm-end">
            <%= paginate @contacts %>
            </div>
        </div>
    </div>

</div>

app/views/contacts/new.html.erb
<div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">New Contact</h2>

              <%= render "form", contact: @contact%>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/contacts/show.html.erb
<div class="container">
    <a class="btn btn-outline-secondary" href="/" role="button">Back</a>
    <div class="row">
        <div class="photo col-12">
            <% if @contact.image.attached? %>
                <%= image_tag(@contact.image) %>
            <% else %>
                <img src="https://cdn-icons-png.flaticon.com/512/149/149071.png">
            <% end %>
            <div class="edit">
                <a class="btn btn-info" href="#" role="button">
                    <%= link_to "Edit", edit_contact_path(@contact) %>
                </a>
                <a class="btn btn-danger" href="#" role="button">
                    <%= link_to "Delete", contact_path(@contact),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %>
                </a>
            </div>
        </div>

    </div>
    <div class="details">
        <div class="row">
        <div class="col-4">
            <h4><b>Name : </b></h4>
            <h4><b>Phone Number : </b></h4>
            <h4><b>Email ID : </b></h4>
            <h4><b>Company Name : </b></h4>
            <h4><b>Date of Birth : </b></h4>
            <h4><b>Address : </b></h4>
        </div>
        <div class="col-4">
            <h4><%= @contact.first_name %> <%= @contact.last_name %></h4>
            <h4><%= @contact.phone_number %></h4>
            <h4><%= @contact.email %></h4>
            <h4><%= @contact.company_name %></h4>
            <h4><%= @contact.birth_date %></h4>
            <h4><%= @contact.address %></h4>
        </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contacts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'contacts', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/boxicons/2.1.0/css/boxicons.min.css" integrity="sha512-pVCM5+SN2+qwj36KonHToF2p1oIvoU3bsqxphdOIWMYmgr4ZqD3t5DjKvvetKhXGc/ZG5REYTT6ltKfExEei/Q==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/5.3.45/css/materialdesignicons.css" integrity="sha256-NAxhqDvtY0l4xn+YVa6WjAcmd94NNfttjNsDmNatFVc=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
  <section class="min-vh-100" style="background-color: #DBDBDB;">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
<a href="/">
<li class="logo-left"><img src="https://raw.githubusercontent.com/vasanthakumar-a/RideEther/master/static/images/RideEther.png"></li>
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-danger my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
    <div class="navbar-text float-right">
    <ul class="navbar-nav mr-auto vas">
        <% if user_signed_in? %>
        <li><%= link_to "Create New Contact", new_contact_path, :class => 'nav-link btn my-2 my-sm-0' %></li>
        <li> <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link btn my-2 my-sm-0' %> </li>
        <li> <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link btn my-2 my-sm-0' %> </li>
        <% else %>
        <li> <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link' %> </li>
        <li> <%= link_to "Login", new_user_session_path, :class => 'nav-link' %> </li>
        <% end %>
    </ul>
    </div>
</nav>
    <%= yield %>
  </section>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <p class="mb-5 pb-lg-2" style="color: #393f81;">Don't have an account?
  <%= link_to "Register here", new_registration_path(resource_name)%></p>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), :class => "small text-muted" %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>